### ISSUE TITLE
Should be the hidden dimension determined by the input dimension in the attetion module?

### ISSUE THREAD

**Issue by ArchNew** [lucidrains/denoising-diffusion-pytorch#237]
In the original DDPM implementation, the hidden dimension is equal to the input dimension of the attention module. In Non-local Neural Networks (X.Wang et al.), the hidden dimension is half of the input dimension. However, this implementation determines the hidden dimension by head number and head dimension. When we set those two parameters, the hidden dimension is set too. It won't change alongside the input dimension. 

My question is: Should the hidden dimension change alongside the input dimension in the attention module?

**Comment by lucidrains** [comment]
ah got it

apologies for closing the other issue too early, thought I understood it

the answer is there are some vision transformer works out there that downsample in stages. some have caught on to gradually increase number of heads and head dimension across stages. however, I have not seen this applied to unets, possibly due to complexity

I can add this! let's leave the issue open

**Comment by lucidrains** [comment]
@ArchNew try setting `attn_heads = (1, 2, 4, 8)` while `dim_head = (16, 32, 64, 64)` in the latest version

**Comment by lucidrains** [comment]
ok, pretty sure i nailed it this time :) closing

**Comment by ArchNew** [comment]
> ok, pretty sure i nailed it this time :) closing

Thanks.
