### ISSUE TITLE
differences on sampling between the paper and your implementation

### ISSUE THREAD

**Issue by animebing** [lucidrains/denoising-diffusion-pytorch#47]
Thanks for sharing your code. When I am reading the code with the DDPM paper, I find that

1. in the paper, the predicted noise is used to compute `mean `directly, then use the `mean `to do sampling
2. in your implementation, the predicted noise is first used to compute `x_start`, then use `x_start` and `x_t` to compute `mean`, then use the `mean` to do sampling

I don't think these two ways are same in the formulation, which confuses me a lot. Can you give me some suggestions about it, thanks

**Comment by askerlee** [comment]
Lucidrains' implementation is (predicted noise -> x_0 -> x_t-1), which uses eq. 9. Routine 1 (predicted noise -> x_t-1) is eq.10. I've verified and they are mathematically equivalent (hint: plugging eq.7 into eq.9).

**Comment by bot66** [comment]
> Lucidrains' implementation is (predicted noise -> x_0 -> x_t-1), which uses eq. 9. Routine 1 (predicted noise -> x_t-1) is eq.10. I've verified and they are mathematically equivalent (hint: plugging eq.7 into eq.9).

I switch the sample method from eq.9 to eq.10, yield very poor quality and unstable samples.

**Comment by MaugrimEP** [comment]
> **Update**: Is the clip op, remove `x_start.clamp_(-1., 1.)` in the implementation, It will also produce bad quality sample which "Algorithm 2 Sampling" produced.

Do you have an idea of when / in which conditions `x_start.clamp_(-1., 1.)` should be used/not be used?

**Comment by AwayGithub** [comment]
@bot66 I notice same results as yours. I don't know why.

**Comment by bot66** [comment]
> [@bot66](https://github.com/bot66) I notice same results as yours. I don't know why.

You could check out this https://github.com/bot66/MNISTDiffusion/issues/2#issuecomment-1818105473

**Comment by AwayGithub** [comment]
@bot66 
I appreciate your response. While I understand that clamping x_0 restricts its range to [-1, 1], I still have the following questions:

1. Why do we first compute x_0 and then derive x_{t-1}? I've noticed this approach in major codebases like DDPM, Palette, and Stable Diffusion, but smaller projects (e.g., [How-Diffusion-Models-Work](https://github.com/Ryota-Kawamura/How-Diffusion-Models-Work) and [annotated-diffusion](https://colab.research.google.com/github/huggingface/notebooks/blob/main/examples/annotated_diffusion.ipynb)) follow DDPM's equation (11) (directly predicting noise -> x_{t-1}) without clamping. I suspect this might relate to image dimensions, as the latter projects work with smaller images and lower-dimensional data, though I'm uncertain. When I modified the Palette project to follow Routine 1, the results were significantly worse.

2. Even with Routine 2, some pixel values in x_{t-1} (computed from clamped x_0) fall outside [-1,1], yet clamping at this stage also yields poor results. This seems reasonable since x_T is initialized from a normal distribution (mean 0, variance 1), naturally containing some outliers beyond [-1,1], and x_{t-1} follows a similar distribution.

3. During early sampling steps, the computed x_0 values exhibit an extremely wide range (on the order of ±1e8 in my case, similar to [this](https://github.com/lucidrains/denoising-diffusion-pytorch/issues/58#issuecomment-1186208177)), necessitating clamping. Why does this occur? My hypothesis is: initial x_t resembles pure Gaussian noise, where the true x_0 (our unknown target) contributes minimally. We expect the network's output ε_θ to closely match x_t (Gaussian noise), making x_0 = (x_t - √(1-ᾱ_t)ε_θ)/√ᾱ_t remain bounded (because 1/√ᾱ_t is very large). However, early in sampling, the network's output differs significantly from x_t, causing extreme x_0 values. What puzzles me is how clamping x_0 leads to its range gradually decreasing during intermediate steps, eventually converging within [-1,1], it's somewhat interesting to me.

**Comment by AwayGithub** [comment]
> > [@bot66](https://github.com/bot66) I notice same results as yours. I don't know why.
> 
> You could check out this [bot66/MNISTDiffusion#2 (comment)](https://github.com/bot66/MNISTDiffusion/issues/2#issuecomment-1818105473)

@bot66
I appreciate your response. While I understand that clamping x_0 restricts its range to [-1, 1], I still have the following questions:

Why do we first compute x_0 and then derive x_{t-1}? I've noticed this approach in major codebases like DDPM, Palette, and Stable Diffusion, but smaller projects (e.g., [How-Diffusion-Models-Work](https://github.com/Ryota-Kawamura/How-Diffusion-Models-Work) and [annotated-diffusion](https://colab.research.google.com/github/huggingface/notebooks/blob/main/examples/annotated_diffusion.ipynb)) follow DDPM's equation (11) (directly predicting noise -> x_{t-1}) without clamping. I suspect this might relate to image dimensions, as the latter projects work with smaller images and lower-dimensional data, though I'm uncertain. When I modified the Palette project to follow Routine 1, the results were significantly worse.

Even with Routine 2, some pixel values in x_{t-1} (computed from clamped x_0) fall outside [-1,1], yet clamping at this stage also yields poor results. This seems reasonable since x_T is initialized from a normal distribution (mean 0, variance 1), naturally containing some outliers beyond [-1,1], and x_{t-1} follows a similar distribution.

During early sampling steps, the computed x_0 values exhibit an extremely wide range (on the order of ±1e8 in my case, similar to https://github.com/lucidrains/denoising-diffusion-pytorch/issues/58#issuecomment-1186208177), necessitating clamping. Why does this occur? My hypothesis is: initial x_t resembles pure Gaussian noise, where the true x_0 (our unknown target) contributes minimally. We expect the network's output ε_θ to closely match x_t (Gaussian noise), making x_0 = (x_t - √(1-ᾱ_t)ε_θ)/√ᾱ_t remain bounded (because 1/√ᾱ_t is very large). However, early in sampling, the network's output differs significantly from x_t, causing extreme x_0 values. What puzzles me is how clamping x_0 leads to its range gradually decreasing during intermediate steps, eventually converging within [-1,1], it's somewhat interesting to me.

**Comment by AwayGithub** [comment]
@bot66 
Update: I've uncovered some new insights.

In the [DDIM](https://github.com/ermongroup/ddim) repository, clamping x_0 during sampling is unnecessary. A related [issue](https://github.com/ermongroup/ddim/issues/2#issuecomment-954360545) was raised, and the authors clarified that clamping had no noticeable impact on results. Subsequent implementations (e.g., LDM, ControlNet) include clamping in DDPM sampling but omit it for DDIM (while still following Routine 2).

This led me to hypothesize: Can clamping be safely removed when reducing sampling steps? I conducted experiments with DDPM, and the results support this claim:

0. Ground Truth vs. Conditional Image:

![Image](https://github.com/user-attachments/assets/e9b086fa-e963-48eb-8087-d1ed4c716529)

1. T=1000 Steps (Full Sampling), clamp vs no-clamp:

![Image](https://github.com/user-attachments/assets/07a8e04d-cba7-4c16-8e1b-a4c30df1d494)

Without clamping, the output is completely black.

2. T=200 Steps, clamp vs no-clamp:

![Image](https://github.com/user-attachments/assets/ecc6d877-af73-4668-a04b-4ee1de91a54a)

Now we have resonable output without clamping, though a little different from the GT.

3. T=100 Steps, clamp vs no-clamp:

![Image](https://github.com/user-attachments/assets/b4d3a2f1-f5ce-444a-92fd-98cdd77d3057)

Again we have output without clamping, but it's worse than output with clamping (though both yield bad output)
